# Generated by Django 3.2.8 on 2021-11-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='doer',
        ),
    ]
