# Generated by Django 3.2.8 on 2021-11-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doer',
            options={},
        ),
        migrations.AlterModelManagers(
            name='doer',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='doer',
            name='username',
        ),
        migrations.AlterField(
            model_name='doer',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='doer',
            name='first_name',
            field=models.CharField(blank=True, max_length=24, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='doer',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into the admin', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='doer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='last_name'),
        ),
    ]
