# Generated by Django 3.2.8 on 2021-11-01 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='doer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list.doer'),
        ),
    ]
