# Generated by Django 3.2.8 on 2021-11-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_task_doer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished')], max_length=12),
        ),
    ]
